import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import ClientLayout from "@/components/ClientLayout";
import { toast } from "sonner";
import { 
  FileText, 
  Download,
  Calendar,
  Filter,
  CheckCircle,
  FileBarChart,
  FilePieChart,
  FileSpreadsheet,
  Eye,
  Printer,
  TrendingUp,
  DollarSign,
  Building2
} from "lucide-react";

type Report = {
  id: number;
  name: string;
  type: string;
  date: string;
  size: string;
  status: "ready" | "generating";
};

export default function Reports() {
  const [filterType, setFilterType] = useState("all");
  const [searchTerm, setSearchTerm] = useState("");

  const reports: Report[] = [
    { id: 1, name: "Portfolio Summary - December 2024", type: "portfolio", date: "2024-12-31", size: "1.2 MB", status: "ready" },
    { id: 2, name: "Investment Statement - Q4 2024", type: "investment", date: "2024-12-31", size: "2.4 MB", status: "ready" },
    { id: 3, name: "Dividend Report - December 2024", type: "dividend", date: "2024-12-30", size: "856 KB", status: "ready" },
    { id: 4, name: "Tax Statement - 2024", type: "tax", date: "2024-12-28", size: "1.8 MB", status: "ready" },
    { id: 5, name: "Property Performance - DHA Phase 6", type: "property", date: "2024-12-25", size: "3.2 MB", status: "ready" },
    { id: 6, name: "Transaction History - 2024", type: "transaction", date: "2024-12-20", size: "1.5 MB", status: "ready" },
    { id: 7, name: "Annual Investment Summary - 2024", type: "annual", date: "2024-12-15", size: "4.1 MB", status: "generating" },
  ];

  const reportStats = [
    { label: "Total Reports", value: "24", icon: FileText, color: "bg-purple-100 text-purple-600" },
    { label: "This Month", value: "7", icon: Calendar, color: "bg-blue-100 text-blue-600" },
    { label: "Tax Documents", value: "4", icon: FileSpreadsheet, color: "bg-green-100 text-green-600" },
  ];

  const getReportIcon = (type: string) => {
    switch (type) {
      case "portfolio": return <FilePieChart className="w-5 h-5 text-purple-600" />;
      case "investment": return <TrendingUp className="w-5 h-5 text-blue-600" />;
      case "dividend": return <DollarSign className="w-5 h-5 text-green-600" />;
      case "tax": return <FileSpreadsheet className="w-5 h-5 text-amber-600" />;
      case "property": return <Building2 className="w-5 h-5 text-indigo-600" />;
      case "transaction": return <FileBarChart className="w-5 h-5 text-pink-600" />;
      default: return <FileText className="w-5 h-5 text-gray-600" />;
    }
  };

  const handleDownload = (report: Report) => {
    if (report.status !== "ready") {
      toast.error("Report is still generating");
      return;
    }
    
    const content = `PropertyPool Investment Report
================================

Report: ${report.name}
Generated: ${report.date}
Investor: Dexter Mcgrowder

Summary:
--------
Total Portfolio Value: PKR 2,500,000
Total Investments: 5 Properties
Total Returns: PKR 125,000 (5%)
Dividend Income: PKR 45,000

Investment Breakdown:
--------------------
1. DHA Phase 6 Apartment - PKR 500,000 (20 shares)
2. Bahria Town Commercial - PKR 750,000 (15 shares)
3. Clifton Sea View - PKR 400,000 (8 shares)
4. Gulberg III Office - PKR 350,000 (7 shares)
5. Model Town Villa - PKR 500,000 (10 shares)

---
Generated by PropertyPool Pakistan
This is an official investment document.
`;
    
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.name.replace(/\s+/g, "_")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Report downloaded successfully!");
  };

  const handlePrint = (report: Report) => {
    if (report.status !== "ready") {
      toast.error("Report is still generating");
      return;
    }
    
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>${report.name}</title>
            <style>
              body { font-family: Arial, sans-serif; padding: 40px; }
              h1 { color: #7c3aed; }
              .header { display: flex; justify-content: space-between; margin-bottom: 30px; border-bottom: 2px solid #7c3aed; padding-bottom: 20px; }
              .logo { font-size: 24px; font-weight: bold; color: #7c3aed; }
              table { width: 100%; border-collapse: collapse; margin-top: 20px; }
              th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
              th { background-color: #f3f4f6; }
              .summary { background: #f9fafb; padding: 20px; border-radius: 8px; margin: 20px 0; }
            </style>
          </head>
          <body>
            <div class="header">
              <div class="logo">PropertyPool</div>
              <div>Generated: ${new Date().toLocaleDateString()}</div>
            </div>
            <h1>${report.name}</h1>
            <div class="summary">
              <h3>Portfolio Summary</h3>
              <p><strong>Total Value:</strong> PKR 2,500,000</p>
              <p><strong>Total Returns:</strong> PKR 125,000 (5%)</p>
              <p><strong>Properties:</strong> 5</p>
            </div>
            <table>
              <thead>
                <tr>
                  <th>Property</th>
                  <th>Investment</th>
                  <th>Shares</th>
                  <th>Returns</th>
                </tr>
              </thead>
              <tbody>
                <tr><td>DHA Phase 6 Apartment</td><td>PKR 500,000</td><td>20</td><td>PKR 25,000</td></tr>
                <tr><td>Bahria Town Commercial</td><td>PKR 750,000</td><td>15</td><td>PKR 37,500</td></tr>
                <tr><td>Clifton Sea View</td><td>PKR 400,000</td><td>8</td><td>PKR 20,000</td></tr>
              </tbody>
            </table>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  const handleView = (report: Report) => {
    toast.info(`Viewing ${report.name}`);
  };

  const filteredReports = reports.filter(report => {
    const matchesType = filterType === "all" || report.type === filterType;
    const matchesSearch = report.name.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesType && matchesSearch;
  });

  return (
    <ClientLayout title="Reports">
      <div className="space-y-6">
        {/* Stats */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {reportStats.map((stat, index) => (
            <Card key={index} className="border-0 shadow-sm">
              <CardContent className="pt-6">
                <div className="flex items-center gap-4">
                  <div className={`w-12 h-12 rounded-xl ${stat.color} flex items-center justify-center`}>
                    <stat.icon className="w-6 h-6" />
                  </div>
                  <div>
                    <p className="text-sm text-gray-500">{stat.label}</p>
                    <p className="text-2xl font-bold text-gray-900">{stat.value}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Filters */}
        <Card className="border-0 shadow-sm">
          <CardContent className="pt-6">
            <div className="flex flex-col md:flex-row gap-4">
              <div className="flex-1">
                <Input
                  placeholder="Search reports..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full"
                />
              </div>
              <Select value={filterType} onValueChange={setFilterType}>
                <SelectTrigger className="w-full md:w-48">
                  <SelectValue placeholder="Filter by type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Reports</SelectItem>
                  <SelectItem value="portfolio">Portfolio</SelectItem>
                  <SelectItem value="investment">Investment</SelectItem>
                  <SelectItem value="dividend">Dividend</SelectItem>
                  <SelectItem value="tax">Tax</SelectItem>
                  <SelectItem value="property">Property</SelectItem>
                  <SelectItem value="transaction">Transaction</SelectItem>
                </SelectContent>
              </Select>
              <Button variant="outline">
                <Filter className="w-4 h-4 mr-2" />
                More Filters
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Reports List */}
        <Card className="border-0 shadow-sm">
          <CardHeader>
            <CardTitle className="text-lg">Your Reports</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {filteredReports.map((report) => (
                <div key={report.id} className="flex items-center justify-between p-4 bg-gray-50 rounded-xl hover:bg-gray-100 transition-colors">
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-xl bg-white shadow-sm flex items-center justify-center">
                      {getReportIcon(report.type)}
                    </div>
                    <div>
                      <h4 className="font-medium text-gray-900">{report.name}</h4>
                      <p className="text-sm text-gray-500">{report.date} • {report.size}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-3">
                    {report.status === "ready" ? (
                      <Badge className="bg-green-100 text-green-700">
                        <CheckCircle className="w-3 h-3 mr-1" />
                        Ready
                      </Badge>
                    ) : (
                      <Badge className="bg-amber-100 text-amber-700">
                        Generating...
                      </Badge>
                    )}
                    <div className="flex gap-1">
                      <Button 
                        variant="ghost" 
                        size="sm"
                        disabled={report.status !== "ready"}
                        onClick={() => handleView(report)}
                        title="View"
                      >
                        <Eye className="w-4 h-4" />
                      </Button>
                      <Button 
                        variant="ghost" 
                        size="sm"
                        disabled={report.status !== "ready"}
                        onClick={() => handleDownload(report)}
                        title="Download"
                      >
                        <Download className="w-4 h-4" />
                      </Button>
                      <Button 
                        variant="ghost" 
                        size="sm"
                        disabled={report.status !== "ready"}
                        onClick={() => handlePrint(report)}
                        title="Print"
                      >
                        <Printer className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                </div>
              ))}

              {filteredReports.length === 0 && (
                <div className="text-center py-12">
                  <FileText className="w-12 h-12 mx-auto text-gray-300 mb-3" />
                  <p className="text-gray-500">No reports found</p>
                </div>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Request Report */}
        <Card className="border-0 shadow-sm bg-gradient-to-r from-purple-50 to-blue-50">
          <CardContent className="pt-6">
            <div className="flex flex-col md:flex-row items-center justify-between gap-4">
              <div>
                <h3 className="font-bold text-gray-900">Need a Custom Report?</h3>
                <p className="text-sm text-gray-600">Request a personalized investment report for your specific needs</p>
              </div>
              <Button className="bg-purple-600 hover:bg-purple-700" onClick={() => toast.success("Report request submitted!")}>
                Request Custom Report
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </ClientLayout>
  );
}
